# Exercise Numpy

Jangan di-run all!. Lakukan run satu per satu pada tiap cell.

In [3]:
import numpy as np

<hr>

### **Nomor 1**

Buatlah sebuah array 1D dengan nama variable myArray yang terdiri dari 36 angka bilangan bulat acak antara 1 dan 100! (Gunakan seed=0)

In [4]:
np.random.seed(0)
myArray = np.random.randint(1, 101, 36)
myArray

array([ 45,  48,  65,  68,  68,  10,  84,  22,  37,  88,  71,  89,  89,
        13,  59,  66,  40,  88,  47,  89,  82,  38,  26,  78,  73,  10,
        21,  81,  70,  80,  48,  65,  83, 100,  89,  50])

<hr>

### **Nomor 2**

Ubahlah array tersebut (myArray) menjadi

* array 2D dengan ukuran 2 x 18
* array 2D dengan ukuran 9 x 4
* array 3D dengan ukuran 2 x 6 X 3

In [5]:
myArray.reshape(2,18)

array([[ 45,  48,  65,  68,  68,  10,  84,  22,  37,  88,  71,  89,  89,
         13,  59,  66,  40,  88],
       [ 47,  89,  82,  38,  26,  78,  73,  10,  21,  81,  70,  80,  48,
         65,  83, 100,  89,  50]])

In [6]:
myArray.reshape(9,4)

array([[ 45,  48,  65,  68],
       [ 68,  10,  84,  22],
       [ 37,  88,  71,  89],
       [ 89,  13,  59,  66],
       [ 40,  88,  47,  89],
       [ 82,  38,  26,  78],
       [ 73,  10,  21,  81],
       [ 70,  80,  48,  65],
       [ 83, 100,  89,  50]])

In [7]:
myArray.reshape(2,6,3)

array([[[ 45,  48,  65],
        [ 68,  68,  10],
        [ 84,  22,  37],
        [ 88,  71,  89],
        [ 89,  13,  59],
        [ 66,  40,  88]],

       [[ 47,  89,  82],
        [ 38,  26,  78],
        [ 73,  10,  21],
        [ 81,  70,  80],
        [ 48,  65,  83],
        [100,  89,  50]]])

<hr>

### **Nomor 3**

Tentukan

* nilai minimum dari array tersebut (myArray)
* nilai maximum dari array tersebut (myArray)
* posisi dari nilai minimum tersebut
* posisi dari nilai maximum tersebut

In [8]:
np.min(myArray)


10

In [9]:
np.max(myArray)

100

In [10]:
np.argmin(myArray)

5

In [11]:
np.argmax(myArray)

33

<hr>

### **Nomor 4**

Buatlah array baru dengan nama variable new_array yang berisi 9 angka yang diambil dari data ke-3, 5, 30, 12, 15, 8, 24, 14, dan 22 dari myArray! 

Ubahlah array tersebut menjadi array 2D dengan ukuran 3 x 3 secara permanen!


In [12]:
posisi = [2, 4, 29, 11, 14, 7, 23, 13, 21]
nilai = myArray[posisi]

new_array = np.array(nilai)
new_array.reshape(3, 3)


array([[65, 68, 80],
       [89, 59, 22],
       [78, 13, 38]])

<hr>

### **Nomor 5**

Tampilkan item pada new_array yang nilainya lebih besar dari 50!

In [13]:
new_array[new_array > 50]

array([65, 68, 80, 89, 59, 78])

<hr>

### **Nomor 6**

Buatlah sebuah array 1D yang berisi angka 0, 25, 50, 75, dan 100 menggunakan fungsi:

* arange
* linspace

In [14]:
np.arange(0,101,25)


array([  0,  25,  50,  75, 100])

In [15]:
np.linspace(0, 100, 5, dtype=int)

array([  0,  25,  50,  75, 100])

<hr>

### **Nomor 7**

Buatlah sebuah array 2D berukuran N X N yang semuanya berisi angka 8, dimana n merupakan bilangan asli yang besarnya dimintakan input kepada user!

contoh :\
N yang diinput adalah: 2

hasil :\
array([[8., 8.],\
&emsp;&emsp;&nbsp;&nbsp;&nbsp;[8., 8.]])

In [17]:
n = 2
np.full((n,n), 8)

array([[8, 8],
       [8, 8]])

<hr>

### **Nomor 8**

Buatlah array 2D dengan nama arrayA berukuran 3 x 4 dengan hasil sebagai berikut :

In [ ]:
arrayA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arrayA

NameError: name 'np' is not defined

Buatlah array 2D dengan nama arrayB berukuran 4 x 1 dengan hasil sebagai berikut :

Gabungkanlah arrayA dan arrayB menjadi arrayC dengan hasil sebagai berikut:

<hr>

### **Nomor 9**

Tampilkan hasil sebagai berikut dengan cara melakukan slicing pada arrayC!

<hr>

### **Nomor 10**

Tampilkan hasil sebagai berikut dengan cara melakukan slicing pada arrayC!