In [1210]:
import time
import numpy as np

In [1211]:
#np.arange(start,stop,step) fungsinya sama seperti for loop
#np.zeros(3) -> array([0,0,0]) fungsinya untuk buat angka 0 aja
#np.eye(4) -> matrix diagonal
#np.linspace(start,end,num) 
# start -> angka awal pada array
# end -> angka akhir pada array
# num -> seberapa banyak angkanya dalam array
#np.random.randn(5,5) -> buat angka random 5x5 = sebanyak 25 angka dalam array
#np.random.randint(1,100,10) buat angka random integer, antara angka 1 sampai 100 sebanyak 10 angka

In [1212]:
size_of_vec =  1000000

def python_calculation():
    start = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i]+Y[i] for i in range(len(X))]
    return time.time() - start

def numpy_calculation():
    start = time.time()
    x = np.arange(size_of_vec)
    y = np.arange(size_of_vec)
    z = x + y
    return time.time() - start

execute_py = python_calculation()
execute_np = numpy_calculation()

print(f'running python {execute_py}')
print(f'running numpy {execute_np}')
print(execute_py/execute_np)

running python 0.25807714462280273
running numpy 0.0056040287017822266
46.052074026802806


In [1213]:
#membuat array menggunakan numpy 1 dimensi
mylist = [1,2,3]
mylist

[1, 2, 3]

In [1214]:
np.array(mylist)

array([1, 2, 3])

In [1215]:
#list 2D
matrix2D = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix2D)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [1216]:
#list 3D
matrix3D = [
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
]
np.array(matrix3D)
# matrix3D[2][1][0] -> 22

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [1217]:
np.zeros(3)

array([0., 0., 0.])

In [1218]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [1219]:
#np.eye(4) -> matrix diagonal
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [1220]:
#np.linspace(start,end,num)
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [1221]:
#buat angka random float
np.random.randn(2)

array([-0.33049675,  0.66678705])

In [1222]:
#buat angka random float 5x5 = sebanyak 25 angka dalam array
np.random.rand(5,5)

array([[0.28445257, 0.72896545, 0.58238262, 0.70448567, 0.5205844 ],
       [0.88761886, 0.08260695, 0.94952367, 0.73425483, 0.14205946],
       [0.7680156 , 0.70583984, 0.6633236 , 0.26482866, 0.34360359],
       [0.27712519, 0.26648512, 0.30196509, 0.95984809, 0.60069382],
       [0.6413254 , 0.69794241, 0.09901342, 0.69988301, 0.35413228]])

In [1223]:
np.random.randint(1,5)

2

In [1224]:
#buat angka random integer, antara angka 1 sampai 100 sebanyak 10 angka
np.random.randint(1,100,10)

array([21, 40, 31, 44, 18, 97, 90, 76, 35, 12])

In [1225]:
np.array(matrix3D)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [1226]:
arr = [1,2,3,4,5,6,7,8,9]
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [1227]:
new_arr = np.array([10,20,3,45,91,12,5,6])
new_arr

array([10, 20,  3, 45, 91, 12,  5,  6])

In [1228]:
new_arr.max()

91

In [1229]:
new_arr.min()

3

In [1230]:
new_arr.argmin()

2

In [1231]:
new_arr.argmax()

4

In [1232]:
new_arr.dtype

dtype('int32')

In [1233]:
arr1 = np.linspace(1,10,15)
arr1

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [1234]:
arr1.dtype

dtype('float64')

In [1235]:
#indexing
arr2 = np.arange(0,11)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [1236]:
arr2[1:20:2]
#karna arr2 tidak sampai 20 maka hanya menampilkan sampai 9

array([1, 3, 5, 7, 9])

In [1237]:
slice_of_arr = arr2[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [1238]:
slice_of_arr [:2] = 10
slice_of_arr

array([10, 10,  2,  3,  4,  5])

In [1239]:
matrix2D

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [1240]:
matrix2D[0:][:1]

[[1, 2, 3]]

In [1241]:
matrix2D[1:][:2]

[[4, 5, 6], [7, 8, 9]]

In [1242]:
#BroadCasting adalah operasi aritmatika pada matrix
arr3 = np.arange(1,10)
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [1243]:
arr3*arr3

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [1244]:
arr_2d = arr3.reshape(3,3)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [1245]:
arr_2d**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [1246]:
arr_1d = np.array([4,5,6])
arr_2d*arr_1d

array([[ 4, 10, 18],
       [16, 25, 36],
       [28, 40, 54]])

In [1247]:
np.sqrt(arr_2d)
#np.exp(arr_2d)
#np.sin(arr_2d)
#np.log(arr_2d)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [1248]:
#other function
#np.insert(arr,5,10) -> memasukkan angka 10 di index ke 5
#np.delete(arr,7) -> menghapus index ke 7
#np.append(arr,11) -> menambah angka 11 ke urutan terakhir
#concatenate
#where

In [1249]:
#aritmatik array
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1250]:
arr+arr*arr

array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])

In [1251]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1252]:
arr_2d = arr.reshape(3,3)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [1253]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1254]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [1255]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [1256]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [1257]:
np.log(arr_2d)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [1258]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1259]:
np.insert(arr,5,10) #index ke 5 berubah value nya jd 10

array([ 1,  2,  3,  4,  5, 10,  6,  7,  8,  9])

In [1260]:
np.delete(arr,7) #angka 8 hilang

array([1, 2, 3, 4, 5, 6, 7, 9])

In [1261]:
np.append(arr,11) #masukin value 11 ke index terakhir

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11])

In [1262]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

In [1263]:
a

array([[1, 2],
       [3, 4]])

In [1264]:
b

array([[5, 6]])

In [1265]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [1266]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])