In [4]:
import numpy as np
import pandas as pd
import seaborn as sns

In [5]:
myNumber = [2, 2, 3, 4, 2, 7, 4, 8, 9, 3, 5]

mean = np.mean(myNumber)
median = np.median(myNumber)
std_dev = np.std(myNumber)
q3 = np.percentile(myNumber, 75)

print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Standard Deviation: {std_dev}")
print(f"Q3: {q3}")

Mean: 4.454545454545454
Median: 4.0
Standard Deviation: 2.3879864611933996
Q3: 6.0


<!-- 
a) Buatlah sebuah array 1 dimensi dari data random integer sebanyak "n", dimana "n" tersebut adalah sebuah input!
b) Batasan random juga ditentukan dalam input.
c) Ubahlah array 1 dimensi tersebut ke dalam bentuk 2 dimensi atau matrix!
d) Setelah diubah ke bentuk 2 dimensi, berisikan pula baliklah urutan datanya! Misalnya dari 1, 2, 3 menjadi 3, 2, 1. 
-->

In [10]:
np.arange(1, 28)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [11]:
np.arange(1, 28).reshape(3, 9)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [12]:
np.arange(1, 28).reshape(3, 3, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
# buatlah sebuah array 2 dimensi dengan ukuran 10x10
# isi dari array tersebut adalah:
# sisi luarnya merupakan angka 4
# selain sisi luar angka yang ditampilkan adalah 0

In [15]:
array = np.full((10, 10), 4)
array[1:-1, 1:-1] = 0
array

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [17]:
array = np.arange(1, 27)
for i in range(26):
    print(chr(i + 97), array[i]) 
    #mengonversi nilai i menjadi karakter huruf kecil

# pd.Series({chr(i+96): i for i in range(1, 27)})

a 1
b 2
c 3
d 4
e 5
f 6
g 7
h 8
i 9
j 10
k 11
l 12
m 13
n 14
o 15
p 16
q 17
r 18
s 19
t 20
u 21
v 22
w 23
x 24
y 25
z 26


In [ ]:
# a) Buatlah sebuah Series menggunakan angka random integer dari 1 hingga 5 sebanyak 100!
# b) Hitunglah banyaknya frekuensi tiap angka! c) Cari tahu 2 nilai dengan frekuensi tertinggi!

In [61]:
np.random.seed(101)
pd.DataFrame(np.random.randint(1, 5, size=100)).value_counts().nlargest(2).reset_index()

0  count
0  4     36
1  1     30

In [ ]:
# a) Import library “seaborn”. Lalu, load data yang bernama “MPG”!
# b) Tampilkan 5 data teratas pada DataFrame dari data “MPG”!
# c) Tampilkan statistik deskriptif atau Describe data selain data numerik!
# d) Tampilkan seluruh nama kolom pada DataFrame!
# e) Hitung Jumlah Missing Value (data kosong) di setiap kolomnya!

In [22]:
mpg_df = sns.load_dataset("mpg")

top_5_mpg = mpg_df.head()
print("5 Data Teratas:")
print(top_5_mpg)

5 Data Teratas:
    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino  


In [23]:
non_numeric_columns = mpg_df.select_dtypes(exclude="number").columns
non_numeric_descriptive_stats = mpg_df[non_numeric_columns].describe()
print("Statistik Deskriptif (Selain Data Numerik):")
print(non_numeric_descriptive_stats)

Statistik Deskriptif (Selain Data Numerik):
       origin        name
count     398         398
unique      3         305
top       usa  ford pinto
freq      249           6


In [24]:
print("Nama Kolom:")
print(mpg_df.columns)

Nama Kolom:
Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')


In [25]:
missing_values = mpg_df.isnull().sum()
print("Jumlah Missing Value di Setiap Kolom:")
print(missing_values)

Jumlah Missing Value di Setiap Kolom:
mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64


In [ ]:
# tampilkan missing value pada kolom horsepower
# tampilkan index lokasi masing value

In [36]:
mpg = sns.load_dataset("mpg")
mpg[mpg['horsepower'].isnull()].index

Index([32, 126, 330, 336, 354, 374], dtype='int64')

In [37]:
#grouping berdasarkan origin dan tampilkan rata2 horsepower
mpg.groupby('origin')['horsepower'].mean()

origin
europe     80.558824
japan      79.835443
usa       119.048980
Name: horsepower, dtype: float64

In [ ]:
# a) Import library "seaborn", lalu load data yang bernama 'MPG'!
# b) Lakukan pengelompokan atau grouping kolom berat 'weight' berdasarkan kolom 'origin' dengan aggregating mean, standar deviasi, sum, count, min, dan max!
# c) Lakukan reset index sehingga kolom 'origin' tidak lagi menjadi index tapi tetap menjadi kolom!

In [39]:

mpg['horse_origin'] = mpg.apply(lambda row: f"lower {row['origin']}" if row['horsepower'] < 105 else f"upper {row['origin']}", axis=1)
mpg.head()

# def create_horse_origin(row):
#     if row['horsepower'] < 105:
#         return f"lower {row['origin']}"
#     else:
#         return f"upper {row['origin']}"

# mpg['horse_origin'] = mpg.apply(create_horse_origin, axis=1)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name horse_origin  
0          70    usa  chevrolet chevelle malibu    upper usa  
1          70    usa          buick skylark 320    upper usa  
2          70    usa         plymouth satellite    upper usa  
3          70    usa              amc rebel sst    upper usa  
4          70    usa                ford torino    upper usa

In [ ]:
# a) Import library "seaborn", lalu load data yang bernama 'MPG'!
# b) Lakukan pengelompokan atau grouping kolom berat 'weight' berdasarkan kolom 'origin' dengan aggregating mean, standar deviasi, sum, count, min, dan max!
# c) Lakukan reset index sehingga kolom 'origin' tidak lagi menjadi index tapi tetap menjadi kolom!


In [64]:
mpg.groupby('origin')['weight'].agg(['mean', 'std', 'sum', 'count', 'min', 'max']).reset_index()

origin         mean         std     sum  count   min   max
0  europe  2423.300000  490.043191  169631     70  1825  3820
1   japan  2221.227848  320.497248  175477     79  1613  2930
2     usa  3361.931727  794.792506  837121    249  1800  5140