# Exercise Numpy

Jangan di-run all!. Lakukan run satu per satu pada tiap cell.

In [1]:
import numpy as np

<hr>

### **Nomor 1**

Buatlah sebuah array 1D dengan nama variable myArray yang terdiri dari 36 angka bilangan bulat acak antara 1 dan 100! (Gunakan seed=0)

array([ 45,  48,  65,  68,  68,  10,  84,  22,  37,  88,  71,  89,  89,
        13,  59,  66,  40,  88,  47,  89,  82,  38,  26,  78,  73,  10,
        21,  81,  70,  80,  48,  65,  83, 100,  89,  50])

<hr>

### **Nomor 2**

Ubahlah array tersebut (myArray) menjadi

* array 2D dengan ukuran 2 x 18
* array 2D dengan ukuran 9 x 4
* array 3D dengan ukuran 2 x 6 X 3

array([[ 45,  48,  65,  68,  68,  10,  84,  22,  37,  88,  71,  89,  89,
         13,  59,  66,  40,  88],
       [ 47,  89,  82,  38,  26,  78,  73,  10,  21,  81,  70,  80,  48,
         65,  83, 100,  89,  50]])

array([[ 45,  48,  65,  68],
       [ 68,  10,  84,  22],
       [ 37,  88,  71,  89],
       [ 89,  13,  59,  66],
       [ 40,  88,  47,  89],
       [ 82,  38,  26,  78],
       [ 73,  10,  21,  81],
       [ 70,  80,  48,  65],
       [ 83, 100,  89,  50]])

array([[[ 45,  48,  65],
        [ 68,  68,  10],
        [ 84,  22,  37],
        [ 88,  71,  89],
        [ 89,  13,  59],
        [ 66,  40,  88]],

       [[ 47,  89,  82],
        [ 38,  26,  78],
        [ 73,  10,  21],
        [ 81,  70,  80],
        [ 48,  65,  83],
        [100,  89,  50]]])

<hr>

### **Nomor 3**

Tentukan

* nilai minimum dari array tersebut (myArray)
* nilai maximum dari array tersebut (myArray)
* posisi dari nilai minimum tersebut
* posisi dari nilai maximum tersebut

<hr>

### **Nomor 4**

Buatlah array baru dengan nama variable new_array yang berisi 9 angka yang diambil dari data ke-3, 5, 30, 12, 15, 8, 24, 14, dan 22 dari myArray! 

Ubahlah array tersebut menjadi array 2D dengan ukuran 3 x 3 secara permanen!


array([[68, 10, 48],
       [89, 66, 37],
       [73, 59, 26]])

<hr>

### **Nomor 5**

Tampilkan item pada new_array yang nilainya lebih besar dari 50!

array([68, 89, 66, 73, 59])

<hr>

### **Nomor 6**

Buatlah sebuah array 1D yang berisi angka 0, 25, 50, 75, dan 100 menggunakan fungsi:

* arange
* linspace

<hr>

### **Nomor 7**

Buatlah sebuah array 2D berukuran N X N yang semuanya berisi angka 8, dimana n merupakan bilangan asli yang besarnya dimintakan input kepada user!

contoh :\
N yang diinput adalah: 2

hasil :\
array([[8., 8.],\
&emsp;&emsp;&nbsp;&nbsp;&nbsp;[8., 8.]])

<hr>

### **Nomor 8**

Buatlah array 2D dengan nama arrayA berukuran 3 x 4 dengan hasil sebagai berikut :

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Buatlah array 2D dengan nama arrayB berukuran 4 x 1 dengan hasil sebagai berikut :

array([[100],
       [200],
       [300],
       [400]])

Gabungkanlah arrayA dan arrayB menjadi arrayC dengan hasil sebagai berikut:

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [100, 200, 300, 400]])

<hr>

### **Nomor 9**

Tampilkan hasil sebagai berikut dengan cara melakukan slicing pada arrayC!

array([[ 7,  8],
       [11, 12]])

<hr>

### **Nomor 10**

Tampilkan hasil sebagai berikut dengan cara melakukan slicing pada arrayC!

200